# Generated by Django 5.2 on 2025-05-01 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='generated_text',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='status',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='title',
        ),
        migrations.AddField(
            model_name='day',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='TransportOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking_url', models.URLField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='itineraries.itinerary')),
            ],
        ),
    ]
