# Generated by Django 5.2 on 2025-05-01 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_remove_itinerary_generated_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking_url', models.URLField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='itineraries.itinerary')),
            ],
        ),
    ]
