# Generated by Django 5.2 on 2025-05-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_hoteloption'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='slots',
            field=models.JSONField(blank=True, help_text='morning/afternoon/weather/etc', null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
