# Generated by Django 5.2 on 2025-05-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_day_slots_alter_day_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteloption',
            old_name='name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='hoteloption',
            name='booking_url',
        ),
        migrations.RemoveField(
            model_name='hoteloption',
            name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='hoteloption',
            name='rating',
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='check_in',
            field=models.DateField(default='2025-05-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='check_out',
            field=models.DateField(default='2025-05-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='platform',
            field=models.CharField(default='airbnb', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='type',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
