# Generated by Django 5.2 on 2025-05-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_rename_name_hoteloption_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteloption',
            name='name',
            field=models.CharField(default='nome', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoteloption',
            name='rating',
            field=models.FloatField(default=4.5),
            preserve_default=False,
        ),
    ]
